WebAppCoreControlInterno/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppCoreControlInterno.Models;
using WebAppCoreControlInterno.Models.ViewModels;

namespace WebAppCoreControlInterno.Controllers
{
    public class BaseController : Controller
    {
        private readonly ControlInternoContext _context;

        public BaseController(ControlInternoContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> IndexBase(string nombre, string sku)
        {
            ViewBag.Nombre = nombre;
            ViewBag.Sku = sku;
            var bases = from m in _context.Bases.Include(m => m.FkIdCategoriaNavigation) select m;

            if (!String.IsNullOrEmpty(nombre))
            {
                bases = bases.Where(m => m.Nombre.Contains(nombre));
            }

            if (!String.IsNullOrEmpty(sku))
            {
                bases = bases.Where(m => m.Sku.Contains(sku));
            }

            return View(await bases.ToListAsync());
        }


        //Pantalla creacion de elementos base
        public IActionResult CrearBase()
        {
            ViewBag.Categorias = new SelectList(_context.Categoria, "IdCategoria", "Nombre");
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearBase(BaseViewModel model)
        {
            var tBase = _context.Bases.Where(m => m.Sku == model.Sku);

            if (tBase.Any())
            {
                ViewBag.ErrorMessage = "Ya existe un Elemento Base con este nombre";
                return View(model);
            }

            if (ModelState.IsValid)
            {

                var bases = new Base()
                {
                    Sku = model.Sku,
                    Nombre = model.Nombre,
                    FkIdCategoria = model.FkIdCategoria,
                    Descripcion = model.Descripcion,
                    Custom1 = model.Custom1,
                    Custom2 = model.Custom2,
                    Custom3 = model.Custom3,
                };
                _context.Add(bases);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexBase));
            }
            ViewBag.Categorias = new SelectList(_context.Categoria, "IdCategoria", "Nombre", model.FkIdCategoria);
            return View(model);
        }



        //Para mostrar el Elemento Base a editar.
        public IActionResult EditarBase(int Id)
        {

            var tBase = _context.Bases.Find(Id);

            BaseViewModel model = new()
            {
                IdBase = tBase.IdBase,
                Nombre = tBase.Nombre,
                Sku = tBase.Sku,
                FkIdCategoria = tBase.FkIdCategoria,
                Descripcion = tBase.Descripcion,
                Custom1 = tBase.Custom1,
                Custom2 = tBase.Custom2,
                Custom3 = tBase.Custom3,
            };
            ViewBag.Categorias = new SelectList(_context.Categoria, "IdCategoria", "Nombre", tBase.FkIdCategoria);
            return View(model);
        }



        //Para editar el Elemento Base.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditarBase( BaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tBase = _context.Bases.Find(model.IdBase);

                tBase.Nombre = model.Nombre;
                tBase.Sku = model.Sku;
                tBase.FkIdCategoria = model.FkIdCategoria;
                tBase.Descripcion = model.Descripcion;
                tBase.Custom1 = model.Custom1;
                tBase.Custom2 = model.Custom2;
                tBase.Custom3 = model.Custom3;

                _context.Entry(tBase).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction(nameof(IndexBase));
            }

            ViewBag.Categorias = new SelectList(_context.Categoria, "IdCategoria", "Nombre", model.FkIdCategoria);
            return View(model);
        }



        //Para confirmar eliminacion de Elemento Base.
        public IActionResult EliminarBase(int Id)
        {
            ViewBag.Errors = false;

            var tElemento = _context.Elementos.Where(m => m.FkIdElementoBase.Equals(Id));

            if (tElemento.Any())
            {
                ViewBag.Errors = true;
            }

            var tBase = _context.Bases.Find(Id);

            BaseViewModel model = new()
            {
                IdBase = tBase.IdBase,
                Nombre = tBase.Nombre,
                Sku = tBase.Sku,
                FkIdCategoria = tBase.FkIdCategoria,
                Descripcion = tBase.Descripcion,
                Custom1 = tBase.Custom1,
                Custom2 = tBase.Custom2,
                Custom3 = tBase.Custom3,
            };

            return View(model);
        }


        //Para eliminar Elemento Base.
        [HttpPost, ActionName("EliminarBase")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmado(int id)
        {
            var tBase = await _context.Bases.FindAsync(id);
            _context.Bases.Remove(tBase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexBase));
        }
    }
}

WebAppCoreControlInterno/Controllers/CargoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppCoreControlInterno.Models;
using WebAppCoreControlInterno.Models.ViewModels;
using PagedList;
using X.PagedList;
using Newtonsoft.Json;

namespace WebAppCoreControlInterno.Controllers
{
    public class CargoController : Controller
    {
        //Se crea la variable para el conexto (BD)
        private readonly ControlInternoContext _context;

        //Se asigna el conexto(BD) a la variable
        public CargoController(ControlInternoContext context)
        {
            _context = context;
        }


        //Para mostrar Vista principal.
        public ViewResult IndexCargo( string cargo, string sortOrder, int? page, string currentFilter )
        {
            ViewBag.Cargo = cargo;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (cargo != null)
            {
                page = 1;
            }
            else
            {
                cargo = currentFilter;
            }

            ViewBag.CurrentFilter = cargo;

            var cargos = from m in _context.Cargos select m;

            if (!String.IsNullOrEmpty(cargo))
            {
                cargos = cargos.Where( m => m.Cargo1.Contains( cargo ) );
            }

            switch (sortOrder)
            {
                case "name_desc":
                    cargos = cargos.OrderByDescending(m => m.Cargo1);
                    break;

                default:
                    cargos = cargos.OrderBy(m => m.Cargo1);
                    break;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(cargos.ToPagedList(pageNumber, pageSize));

            //return View(await cargos.ToListAsync());
        }



        ////Para mostrar Vista principal.
        //public async Task<IActionResult> IndexCargo(string cargo, string sortOrder, int? page, string currentFilter)
        //{
        //    ViewBag.Cargo = cargo;
        //    ViewBag.CurrentSort = sortOrder;
        //    ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

        //    if (cargo != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        cargo = currentFilter;
        //    }

        //    ViewBag.CurrentFilter = cargo;

        //    var cargos = from m in _context.Cargos select m;

        //    if (!String.IsNullOrEmpty(cargo))
        //    {
        //        cargos = cargos.Where(m => m.Cargo1.Contains(cargo));
        //    }

        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            cargos = cargos.OrderByDescending(m => m.Cargo1);
        //            break;

        //        default:
        //            cargos = cargos.OrderBy(m => m.Cargo1);
        //            break;
        //    }

        //    int pageSize = 3;
        //    int pageNumber = (page ?? 1);
        //    return View(cargos.ToPagedList(pageNumber, pageSize));

        //    //return View(await cargos.ToListAsync());
        //}



        ////Para mostrar Vista para Crear.
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //Para crear empleados
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CargoViewModel model)
        {
            //System.Diagnostics.Debug.WriteLine( JsonConvert.SerializeObject(model) );

            var tCargo = _context.Cargos.Where(m => m.Cargo1.Equals(model.Cargo1));

            if (tCargo.Any())
            {
                ViewBag.ErrorMessage = "Ya existe un Cargo con este nombre";
                return View(model);
            }

            if (ModelState.IsValid)
            {
                Cargo cargo = new()
                {
                    Cargo1 = model.Cargo1
                };

                _context.Add(cargo);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(IndexCargo));
            }
            return View(model);
        }


        //Para mostrar el Cargo a editar.
        public IActionResult Editar(int Id)
        {
            var oCargo = _context.Cargos.Find(Id);

            CargoViewModel model = new()
            {
                IdCargo = oCargo.IdCargo,
                Cargo1 = oCargo.Cargo1,
            };
            

            return View(model);
        }


        //Para editar Cargo.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar( [Bind(include:"IdCargo, Cargo1")] CargoViewModel model)
        {
            if ( ModelState.IsValid )
            {
                var tCargo = _context.Cargos.Find(model.IdCargo);

                //System.Diagnostics.Debug.WriteLine(model.IdCargo + " - el id que llega");
                tCargo.Cargo1 = model.Cargo1;

                _context.Entry(tCargo).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction(nameof(IndexCargo));
            }
            return View(model);
        }


        //Para confirmar eliminacion de Cargo.
        public IActionResult Eliminar(int Id)
        {
            ViewBag.Errors = false;
            var oCargo = _context.Cargos.Find(Id);
            var empleado = _context.Empleados.Where(m => m.FkIdCargo.Equals(Id));

            if (empleado.Any())
            {
                ViewBag.Errors = true;
            }

            CargoViewModel model = new()
            {
                IdCargo = oCargo.IdCargo,
                Cargo1 = oCargo.Cargo1,
            };


            return View(model);
        }


        //Para eliminar Cargo.
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmado(int id)
        {
            var cargo = await _context.Cargos.FindAsync(id);
            _context.Cargos.Remove(cargo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexCargo));
        }
    }
}

WebAppCoreControlInterno/Controllers/LeerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppCoreControlInterno.Impinj;
using WebAppCoreControlInterno.Models.ViewModels;

namespace WebAppCoreControlInterno.Controllers
{
    public class LeerController : Controller
    {
        [Route("Ruta1")]
        public IActionResult IndexLeer()
        {
            return View();
        }

        [Route("Ruta2")]
        public IActionResult IndexLeer( LeerViewModel m )
        {
            Reader r = new();
            m.Data = r.CrearLectura().Result;
            return View(m);
        }
    }
}

WebAppCoreControlInterno/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-cl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Templiner - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Templiner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                    aria-controls="mainNavbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ms-auto" id="mainNavbar">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administracion" asp-action="Index">Administración</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reporte" asp-action="IndexReporte">Reportes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leer" asp-action="IndexLeer">Leer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
        <main role="main" class="">
            @RenderBody()
        </main>
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppCoreControlInterno - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppCoreControlInterno/Views/Shared/_NavbarAdministracion.cshtml
<nav class="navbar navbar-expand-lg bg-white navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Administración</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="IndexEmpleado">Empleados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cargo" asp-action="IndexCargo">Cargos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Estado" asp-action="IndexEstado">Estados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="IndexCategoria">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Base" asp-action="IndexBase">Elementos Base</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Elemento" asp-action="IndexElemento">Elementos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="IndexSucursal">Sucursales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Sector" asp-action="IndexSector">Sectores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="SubSector" asp-action="IndexSubSector">Subsectores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Lector" asp-action="IndexLector">Lectores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Antena" asp-action="IndexAntena">Antenas</a>
                </li>
            </ul>
        </div>
    </div>
</nav>